### ISSUE TITLE
Criar um endpoint para contar quantidades de letras de um palindromo.

### ISSUE THREAD

**Issue by pcampos119104** [john-cleese/palindromo#30]
Um endpoint que recebe um palindromo e retorna a quantidade de letras. Se não for um palindromo retorna uma mensagem de erro
```
{
 'msg': 'Frase informada não é um palindromo '
}
```
[restful](https://restfulapi.net)

**Comment by lfcarlos** [comment]
Issuei finalizada em 10/12/22
